In [1]:
import tensorflow as tf

In [2]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142]

In [3]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]), name= 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name= 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name= 'weight3')
b = tf.Variable(tf.random_normal([1]), name= 'bias')
# ([1]) 그냥 각각 하나의 값이라는 뜻

In [6]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [7]:
# cost func
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Launch the graph in a session
s = tf.Session()

In [13]:
s.run(tf.global_variables_initializer())

In [14]:
for step in range (2001):
    cost_val, hy_val, _ = s.run([cost, hypothesis, train],
                               feed_dict = {x1: x1_data, x2:x2_data, x3:x3_data,Y:y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  4339.88 
Prediction:
 [  91.44682312  115.72288513  111.30605316  118.66836548   91.65782166]
100 Cost:  3.83585 
Prediction:
 [ 149.93702698  185.9030304   180.51817322  194.03614807  145.1595459 ]
200 Cost:  3.68504 
Prediction:
 [ 149.9990387   185.8600769   180.53660583  194.05393982  145.09944153]
300 Cost:  3.54202 
Prediction:
 [ 150.05932617  185.81829834  180.55448914  194.07130432  145.0408783 ]
400 Cost:  3.40631 
Prediction:
 [ 150.11795044  185.77764893  180.5718689   194.08831787  144.98381042]
500 Cost:  3.27758 
Prediction:
 [ 150.17497253  185.7381134   180.58879089  194.10494995  144.92822266]
600 Cost:  3.15546 
Prediction:
 [ 150.23042297  185.69966125  180.60519409  194.12123108  144.87408447]
700 Cost:  3.03958 
Prediction:
 [ 150.28431702  185.66229248  180.62113953  194.13717651  144.82130432]
800 Cost:  2.9296 
Prediction:
 [ 150.33673096  185.62591553  180.63664246  194.15275574  144.76986694]
900 Cost:  2.82524 
Prediction:
 [ 150.38771057  185.59049

** 점점 y_data의 152, 185, 180, 196, 142와 비슷한 수준으로 수렴하고 있음을 확인 가능 **

-----
### 위와 같은 방법은 더이상 사용하지 말자! 데이터가 많아지면 커버가 안됨

# Using Matrix

In [15]:
x_data = [[73.,80.,75.], [93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data = [[152.], [185.],[180.],[196.],[142.]]

x의 [x1, x2, x3] 하나의 instance에 맞는 y data를 적으므로 더 이해하기 쉽다. <br>
e.g. [73.,80.,75.] -> [152.]

In [17]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

tf.placeholder(tf.float32, shape = [None, 3])에서 <br>
현재 예제에서는 5개이지만 장차 n개(미정)가 좋으므로 None으로 표시 <br>
x1, x2, x3 -> 3개이므로 [None,3]으로 표시

In [18]:
W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [19]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b