# Simple ID array and slicing

In [8]:
import tensorflow as tf
import numpy as np
import pprint as pp

In [9]:
tf.set_random_seed(777)

In [10]:
pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

# Simple Array

In [11]:
t = np.array([0,1,2,3,4,5,6])
pp.pprint(t)
print(t.ndim)  # rank
print(t.shape) # shape
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

array([0, 1, 2, 3, 4, 5, 6])
1
(7,)
0 1 6
[2 3 4] [4 5]
[0 1] [3 4 5 6]


* rank: 몇 차원 array냐
* shape: 이 array가 어떻게 생겼냐

# 2D Array

In [13]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


# Shape, Rank, Axis

In [14]:
t=tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [15]:
t = tf.constant([[1,2],
                [3,4]])
tf.shape(t).eval()

array([2, 2])

In [18]:
t = tf.constant([[[[1,2,3,4],[5,6,7,8],[9,10,11,12]],
                 [[13,14,15,16],[17,18,19,20],[21,22,23,24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

* 쉽게 말해 rank는 bracket의 갯수와도 같다
* shape은 끝까지 들어가서 그곳에 있는 원소의 갯수를 제일 뒤에서부터 채워온다. [1,2,3,4]
* axis의 경우에는 가장 안에 있으면 3, 그다음은 2, ... 가장 바깥에 있는 축은 0
* 가장 안쪽에 있는 축의 경우 -1이라고도 부른다.

_결국 (?, ?,...,?) 물음표의 갯수를 결정 짓는 것은 **Rank**_ <br>
_가장 마지막 물음표는 한 array의 elements 수 (?,..,2)_ <br>
_그 elements를 가지고 있는 집합의 수가 그 앞에 물음표를 채운다. [1,2], [3,4] 두개씩 든게 2개이므로 [2,2]_

# Matmul Vs. Multiply

In [20]:
m1 = tf.constant([[1,2],[3,4]])
m2 = tf.constant([[1],[2]])
print("m1 shape", m1.shape)
print("m2 shape",m2.shape)

m1 shape (2, 2)
m2 shape (2, 1)


In [23]:
tf.matmul(m1,m2).eval()

array([[ 5],
       [11]])

In [24]:
(m1*m2).eval()

array([[1, 2],
       [6, 8]])

위 둘의 결과는 매우 다르다.
그 이유는 Broadcating 때문이다.

In [25]:
matrix1 = tf.constant([[1,2]])
matrix2 = tf.constant(3)
(matrix1+matrix2).eval()

array([[4, 5]])

output을 보면 알듯이 shape이 다른데도 연산이 되었고 (3)이 [[3,3]]으로 변화됐다.

# Reduce mean

In [26]:
tf.reduce_mean([1,2],axis=0).eval()

1

In [27]:
x=[[1.,2.],
  [3.,4.]]
tf.reduce_mean(x).eval()

2.5

# Reduce sum

In [30]:
tf.reduce_sum(x).eval()

10.0

In [32]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [34]:
tf.reduce_sum(x,axis=1).eval()

array([ 3.,  7.], dtype=float32)

In [36]:
tf.reduce_sum(x,axis=-1).eval()

array([ 3.,  7.], dtype=float32)

가로 방향은 axis = 1, -1 <br>
세로 방향은 axis = 0

In [37]:
tf.reduce_mean(tf.reduce_sum(x,axis=-1)).eval()

5.0

# Argmax

In [38]:
x=[[0,1,2],
  [2,1,0]]
tf.argmax(x,axis=0).eval()

array([1, 0, 0], dtype=int64)

In [39]:
tf.argmax(x,axis=1).eval()

array([2, 0], dtype=int64)

**argmax는 가장 큰 것의 위치가 어디냐는 말<br>**
그러므로 axis=1이면 가로로 봤을 때<br>
[0,1,2]에서 2번째 있는 2가 제일 크므로 2<br>
[2,1,0]에선 0번째 있는 2가 제일 크므로 0<br>
따라서[2,0]

# Reshape **
중요합니다!

In [42]:
t = np.array([[[0,1,2],
               [3,4,5]],
             
               [[6,7,8],
               [9,10,11]]])
t.shape

(2, 2, 3)

rank가 3, rank 3인게 2개, rank 3이거 2개짜리가 또 2개

In [44]:
tf.reshape(t,shape=[-1,3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

element는 3, 나머지는 너가 알아서해 (그 명령어가 -1)

In [45]:
tf.reshape(t, shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### Reshape(squeeze, expand)

In [46]:
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2])

In [47]:
tf.expand_dims([0,1,2],1).eval()

array([[0],
       [1],
       [2]])

# One hot

In [48]:
tf.one_hot([[0],[1],[2],[0]],depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

[0]이니 첫번째를 hot 하게 만들었고 결과는 [1,0,0] <br>
[1]이니 두번째를 hot 하게 만들었고 결과는 [0,1,0] <br>

In [49]:
tf.one_hot([[0],[1],[2],[0]],depth=4).eval()

array([[[ 1.,  0.,  0.,  0.]],

       [[ 0.,  1.,  0.,  0.]],

       [[ 0.,  0.,  1.,  0.]],

       [[ 1.,  0.,  0.,  0.]]], dtype=float32)

** 잘 살펴보면 input은 rank=2고 output은 rank = 3으로 자동적으로 변환됐음을 알 수 있다.**<br>
이게 싫으면 reshape하셈

In [52]:
tt=tf.one_hot([[0],[1],[2],[0]],depth=4).eval()
tf.reshape(tt,shape=[-1,4]).eval()

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.]], dtype=float32)

# Casting

In [53]:
tf.cast([1.8,2.2,3.3,4.9], tf.int32).eval()

array([1, 2, 3, 4])

float형태가 int로 바뀌면서 소숫점이 모두 사라졌다.

In [54]:
tf.cast([True, False, 1==1,0==1],tf.int32).eval()

array([1, 0, 1, 0])

True, False를 숫자로 바꿔서 셀때 아주 좋음

# Stack

In [55]:
x=[1,4]
y=[2,5]
z=[3,6]

# Pack along first dim
tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
tf.stack([x,y,z],axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
tf.stack([x,y,z],axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

# Ones and Zeros like

In [58]:
x = [[0,1,2],
     [2,1,0]]
tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [59]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

# Zip

In [60]:
for x,y in zip ([1,2,3],[4,5,6]):
    print(x,y)

1 4
2 5
3 6


In [61]:
for x,y,z in zip([1,2,3], [4,5,6],[7,8,9]):
    print(x,y,z)

1 4 7
2 5 8
3 6 9
