In [1]:
import os

In [2]:
print (os.getcwd())

C:\Users\Damian\Dropbox\Study\Machine Learning\sungkim


In [7]:
import numpy as np

In [9]:
data = np.loadtxt('data-01-test-score.txt',delimiter=',',dtype=np.float32)

In [10]:
x_data = data[:,0:-1]
y_data = data[:,[-1]]

In [12]:
# Make sure the shape and data are OK
print(x_data.shape,x_data,len(x_data))
print(y_data.shape,y_data)

(6, 3) [[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]] 6
(6, 1) [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]]


# Indexing, Slicing, Iterating

* Arrays can be indexed, sliced, iterated much like lists and other sequence types in Python <br>
* As with Python lists, slicing in NumPy can be accomplished with the colon(:) syntax<br>
* Colon instances(:) can be replaced with dots(...)

In [14]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [15]:
a[1:3]

array([2, 3])

In [16]:
a[-1]

5

In [18]:
a[0:2] = 9
a

array([9, 9, 3, 4, 5])

In [20]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
b[:,1]

array([ 2,  6, 10])

In [22]:
b[-1]

array([ 9, 10, 11, 12])

In [23]:
b[-1,:]

array([ 9, 10, 11, 12])

In [24]:
b[-1,...]

array([ 9, 10, 11, 12])

In [25]:
b[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# 적용

In [26]:
import tensorflow as tf
import numpy as np

In [27]:
tf.set_random_seed(7777) # for reproducibility

In [32]:
data = np.loadtxt('data-01-test-score.txt',delimiter=',',dtype=np.int32)

In [33]:
x_data = data[:,0:-1]
y_data = data[:,[-1]]

In [34]:
# Make sure the shape and data are OK
print(x_data.shape,x_data,len(x_data))
print(y_data.shape,y_data)

(6, 3) [[ 73  80  75]
 [ 93  88  93]
 [ 89  91  90]
 [ 96  98 100]
 [ 73  66  70]
 [ 53  46  55]] 6
(6, 1) [[152]
 [185]
 [180]
 [196]
 [142]
 [101]]


In [36]:
# Placeholders for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape = [None,3])
Y = tf.placeholder(tf.float32, shape = [None,1])

In [37]:
W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [38]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b

In [39]:
# Simplified cost function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [40]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [41]:
# session
s = tf.Session()

In [42]:
s.run(tf.global_variables_initializer())

In [43]:
for step in range (2001):
    cost_val, hy_val, _ = s.run(
        [cost, hypothesis, train],
        feed_dict={X:x_data, Y:y_data})
    if step % 100 ==0:
        print(step, "Cost: ",cost_val,
             "\nPrediction:\n",hy_val)

0 Cost:  14671.5 
Prediction:
 [[ 265.24472046]
 [ 320.85095215]
 [ 315.17233276]
 [ 342.38830566]
 [ 245.87657166]
 [ 180.10481262]]
100 Cost:  1.05323 
Prediction:
 [[ 151.57717896]
 [ 184.15713501]
 [ 180.52482605]
 [ 195.74691772]
 [ 141.60638428]
 [ 103.22164917]]
200 Cost:  1.03972 
Prediction:
 [[ 151.59738159]
 [ 184.14807129]
 [ 180.53367615]
 [ 195.74977112]
 [ 141.59672546]
 [ 103.20008087]]
300 Cost:  1.02694 
Prediction:
 [[ 151.6169281 ]
 [ 184.139328  ]
 [ 180.54225159]
 [ 195.75245667]
 [ 141.58746338]
 [ 103.17913818]]
400 Cost:  1.01483 
Prediction:
 [[ 151.63583374]
 [ 184.13090515]
 [ 180.55055237]
 [ 195.75498962]
 [ 141.57861328]
 [ 103.15878296]]
500 Cost:  1.00338 
Prediction:
 [[ 151.65414429]
 [ 184.12277222]
 [ 180.55862427]
 [ 195.75735474]
 [ 141.57015991]
 [ 103.13902283]]
600 Cost:  0.99252 
Prediction:
 [[ 151.67185974]
 [ 184.11489868]
 [ 180.56642151]
 [ 195.75956726]
 [ 141.5620575 ]
 [ 103.11981201]]
700 Cost:  0.982242 
Prediction:
 [[ 151.68899536]

In [45]:
# Ask My Score
print("Your score will be ", s.run(hypothesis,
                                  feed_dict={X:[[100,70,101]]}))
print("Other scores will be ",s.run(hypothesis,
                                   feed_dict={X:[[60,70,110],[90,100,80]]}))

Your score will be  [[ 182.96908569]]
Other scores will be  [[ 143.90979004]
 [ 183.87869263]]


# Queue Runner 이용

여러 개의 파일을 Queue에 쌓고 Reader로 읽어와서 decode하고 Example Queue에 다시 쌓는다.

1_**파일 불러오기**

``` filename_queue =tf.train.string_input_producer(
    ['data-01-test-score.csv', 'data-02-test-score.csv', ...],
    shuffle=False, name='filename_queue') ```


2_** Reader 정의**

~~~
reader=tf.TextLineReader()
key, value = reader.read(filename_queue) 
~~~

* text파일을 읽어올 때 일반적으로 사용

3_** Value의 Parsing**

```
record_defaults=[[0.],[0.],[0.],[0.]]
xy=tf.decode_csv(value, record_defaults=record_defaults)```

- 각각에 필드에 데이터 타입에 대해 정해줄 수가 있음 <br>
 여기서는 float이라 모두 [0.]으로 정의

4_**tf.train.batch**

batch라는 것으로 읽어오면 일종의 펌프같은 역할을 해줌

```
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:,-1],xy[-1:]], batch_size =10)
sess = tf.Session()
```

batch_size는 한 번에 몇 개 가져올 것인가를 묻는 것

5_ **통상적인 batch 나머지 부분**

```
# Start populating the filename queue.
coord=tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess,coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    ...
   
   coord.request_stop()
   coord.join(threads)
   ```

- 추후에 ... 부분에서 feed_dict 같은 방법을 사용해서 x_batch, y_batch로 값을 넘겨주면 된다.