# Training and Test datasets

In [3]:
import tensorflow as tf

In [1]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [2]:
# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [5]:
X = tf.placeholder("float",[None,3])
Y = tf.placeholder("float",[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [6]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [12]:
# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [13]:
# Launch Graph
with tf.Session() as sess:
    # Initialze TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict = {X:x_data, Y:y_data})
        print(step,cost_val,W_val)
        # 여기까지가 학습
        
    # predict
    print("Prediction: ",sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ",sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 1.17838 [[-2.41861296 -0.59061128 -0.23049025]
 [-0.53656769 -1.19469595 -0.54923177]
 [-0.16834448 -0.24236169 -0.88849837]]
1 1.01797 [[-2.42350149 -0.60905993 -0.20715299]
 [-0.55132073 -1.22232413 -0.5068506 ]
 [-0.17193134 -0.27828181 -0.84899139]]
2 0.971545 [[-2.42829394 -0.61973941 -0.19168106]
 [-0.56357086 -1.21371567 -0.50320894]
 [-0.17530949 -0.27969766 -0.84419739]]
3 0.962998 [[-2.43103075 -0.63082731 -0.17785636]
 [-0.56355983 -1.20861602 -0.50831962]
 [-0.1673924  -0.28459585 -0.84721631]]
4 0.955384 [[-2.43463588 -0.64118367 -0.16389488]
 [-0.56845671 -1.20031762 -0.51172107]
 [-0.16430405 -0.28616306 -0.84873742]]
5 0.947986 [[-2.43784904 -0.65173584 -0.15012962]
 [-0.57097614 -1.19377923 -0.5157401 ]
 [-0.15908627 -0.28933159 -0.85078669]]
6 0.940743 [[-2.44125748 -0.662018   -0.136439  ]
 [-0.5745014  -1.18652904 -0.51946503]
 [-0.15498006 -0.29164448 -0.85257995]]
7 0.933642 [[-2.44458318 -0.67225796 -0.12287337]
 [-0.57743269 -1.17977154 -0.52329117]
 [-0.15044

 [ 0.03629601 -0.35907865 -0.97642154]]
85 0.651228 [[-2.71805692 -1.1772542   0.65559638]
 [-0.654971   -0.89195549 -0.73356849]
 [ 0.03765641 -0.35892677 -0.97793382]]
86 0.649538 [[-2.72156096 -1.1810019   0.66284817]
 [-0.65485758 -0.89037758 -0.73525983]
 [ 0.03900627 -0.35876536 -0.9794451 ]]
87 0.64787 [[-2.72506213 -1.18470347  0.67005098]
 [-0.65473503 -0.8888281  -0.73693186]
 [ 0.04034609 -0.35859495 -0.9809553 ]]
88 0.646226 [[-2.72856045 -1.18835974  0.67720544]
 [-0.6546039  -0.88730627 -0.73858482]
 [ 0.04167605 -0.35841578 -0.98246443]]
89 0.644604 [[-2.73205566 -1.19197118  0.68431216]
 [-0.65446454 -0.88581151 -0.74021894]
 [ 0.0429966  -0.35822827 -0.98397249]]
90 0.643005 [[-2.73554778 -1.19553864  0.69137174]
 [-0.65431726 -0.88434327 -0.74183452]
 [ 0.04430807 -0.35803279 -0.98547941]]
91 0.641427 [[-2.7390368  -1.19906259  0.69838476]
 [-0.65416247 -0.88290089 -0.74343169]
 [ 0.04561075 -0.35782969 -0.98698521]]
92 0.63987 [[-2.74252272 -1.20254374  0.70535177]
 

# Learning rate: NaN!

크면 overshooting <br>
작으면 변화 속도가 느림

# Non-normalized inputs

결과 데이터가 이상하게 나오는 경우 의심

MinMaxSclaer를 통한 normalized를 한다.

xy=MinMaxScaler(xy) <br>
print(xy)